[package]
name = "alphonse-arkime"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
elasticsearch = { version = "7.12.1-alpha.1", features = ["rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
