[workspace]
members = [
    "app",
    "api",
    "parsers/http",
    "parsers/misc",
    "parsers/simple-writer",
    "parsers/tls",
    "parsers/ip",
    "rx-drivers/libpcap",
    "rx-drivers/files",
]
resolver = "2"
