[package]
name = "udp"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "udp"

[dependencies]
alphonse-api = { path = "../../api", version = "0.1.0" }
anyhow = "1.0"
serde_json = "1.0"
