[package]
name = "libpcap"
version = "0.1.0"
authors = ["Jack Liar"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "rxlibpcap"

[dependencies]
alphonse-api = { path="../../api", optional=false }
anyhow = "1.0"
crossbeam-channel = "0.5"
elasticsearch = { version="7.12.1-alpha.1", features=["rustls-tls"], optional=true }
fnv = "1.0"
libc = "0.2"
pcap = "0.8"
serde = "1.0"
tokio = { version="1", optional=true, features=["net", "time"] }

[features]
arkime = ["elasticsearch", "tokio"]
default = ["arkime"]
