[package]
name = "tcp"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
name = "tcp"

[dependencies]
alphonse-api = { path = "../../api", version = "0.1.0" }
alphonse-utils = { path = "../../utils", features = ["tcp-reassembly"] }
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"
